version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/home/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email artur@topia.us --agree-tos --no-eff-email --force-renewal -d topia.us -d www.topia.us

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
